### ISSUE TITLE
Poner proxy a npm

### ISSUE THREAD

**Issue by juusechec** [GLUD/distroCustomization#1]
Se necesita que el script le ponga el proxy a npm
https://stackoverflow.com/questions/25660936/using-npm-behind-corporate-proxy-pac

**Comment by juusechec** [comment]
https://flight-manual.atom.io/getting-started/sections/installing-atom/#proxy-and-firewall-settings

**Comment by MauricioAcosta** [comment]
En el siguiente commit se crearon las dos funciones para colocar el proxy a npm
https://github.com/GLUD/distroCustomization/tree/proxy_npm

**Comment by juusechec** [comment]
Todo parece correcto https://github.com/GLUD/distroCustomization/pull/3
